-- ============================================================================
--  UniVibe — Platform Backend (Supabase / PostgreSQL)
--  Run this in the Supabase SQL Editor, or via:
--      supabase db push   /   psql "$DATABASE_URL" -f db/schema.sql
--
--  Everything the frontend calls lives here: tables, Row Level Security,
--  stored functions (the app talks to the DB ONLY through these), the
--  "gossip" storage bucket and realtime for the live chat.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. TABLES
-- ---------------------------------------------------------------------------

-- profiles: 1:1 mirror of auth.users, holds the public username
create table if not exists public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  username   text not null unique check (char_length(username) between 3 and 20),
  created_at timestamptz not null default now()
);

-- gossipbar: the posts ("gossips")
-- images holds up to 2 filenames (reference the "gossip" storage bucket)
create table if not exists public.gossipbar (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users (id) on delete set null,
  username   text not null,                       -- denormalised so feeds need no join
  title      text not null check (char_length(title) <= 300),
  content    text not null,                       -- HTML from the rich text editor
  images     text[2],                             -- [filename_1, filename_2] or nulls
  likes      bigint not null default 0,
  created_at timestamptz not null default now()
);

-- likes: one row per (user, post) — enables toggling + "isliked" flag
create table if not exists public.likes (
  user_id    uuid not null references auth.users (id) on delete cascade,
  post_id    bigint not null references public.gossipbar (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

-- messages: the Campus Connect live chat feed (streamed via Supabase Realtime)
create table if not exists public.messages (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users (id) on delete cascade,
  username   text not null,
  message    text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 2. INDEXES
-- ---------------------------------------------------------------------------
create index if not exists gossipbar_created_idx on public.gossipbar (created_at desc);
create index if not exists likes_post_idx        on public.likes (post_id);
create index if not exists messages_created_idx  on public.messages (created_at desc);

-- ---------------------------------------------------------------------------
-- 3. ROW LEVEL SECURITY
--    The UI never touches tables directly — it calls the RPC functions below
--    (SECURITY DEFINER), so base tables can be locked down.
-- ---------------------------------------------------------------------------
alter table public.profiles  enable row level security;
alter table public.gossipbar enable row level security;
alter table public.likes     enable row level security;
alter table public.messages  enable row level security;

-- gossipbar is readable by everyone (feed + shared-post links).
create policy "gossipbar_select" on public.gossipbar for select using (true);

-- profiles / likes / messages have no direct-table policies on purpose:
-- every write happens inside the SECURITY DEFINER functions below.

-- ---------------------------------------------------------------------------
-- 4. STORED FUNCTIONS (RPC) — the backend API
--    security definer + search_path = public
--    => callers can only do exactly what these functions allow.
-- ---------------------------------------------------------------------------

-- Auth: is the username already taken? (returns TRUE = taken)
create or replace function public.checkusername(p_username text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where lower(username) = lower(p_username)
  );
$$;

-- Auth: create / refresh the profile for a freshly signed-up user
create or replace function public.insertusername(p_id uuid, p_username text)
returns boolean
language sql
security definer
set search_path = public
as $$
  insert into public.profiles (id, username)
  values (p_id, p_username)
  on conflict (id) do update set username = excluded.username
  returning true;
$$;

-- Auth: fetch a user's username after login (cached in localStorage by the SPA)
create or replace function public.get_username(p_user_id uuid)
returns text
language sql
security definer
set search_path = public
as $$
  select username from public.profiles where id = p_user_id;
$$;

-- Posts: create a gossip (images arrives as jsonb {0|1: filename|null} from JS)
create or replace function public.insert_into_gossipbar(
  p_uuid    uuid,
  p_title   text,
  p_content text,
  p_images  jsonb
)
returns bigint
language sql
security definer
set search_path = public
as $$
  insert into public.gossipbar (user_id, username, title, content, images, likes)
  select p_uuid, author.username, p_title, p_content,
         array[p_images->>0, p_images->>1]::text[], 0
  from public.profiles author
  where author.id = p_uuid
  returning id;
$$;

-- Posts: paginated feed (limit/offset) with the viewer's "isliked" flag
create or replace function public.fetch_posts(
  user_uuid    uuid,
  limit_count  integer,
  offset_count integer
)
returns table (
  id bigint, username text, title text, content text, images text[],
  likes int, isliked boolean, created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select gb.id, gb.username, gb.title, gb.content, gb.images::text[], gb.likes::int,
         exists (select 1 from public.likes l
                 where l.post_id = gb.id and l.user_id = user_uuid) as isliked,
         gb.created_at
  from public.gossipbar gb
  order by gb.created_at desc
  limit limit_count offset offset_count;
$$;

-- Posts: one post by id (renders shared links, e.g. /post.html?id=…)
create or replace function public.fetch_shared_posts(
  user_uuid uuid,
  post_id   bigint
)
returns table (
  id bigint, username text, title text, content text, images text[],
  likes int, isliked boolean, created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select gb.id, gb.username, gb.title, gb.content, gb.images::text[], gb.likes::int,
         exists (select 1 from public.likes l
                 where l.post_id = gb.id and l.user_id = user_uuid) as isliked,
         gb.created_at
  from public.gossipbar gb
  where gb.id = post_id;
$$;

-- Posts: only MY posts (profile → "View Posted Gossip")
create or replace function public.fetch_my_posts(
  user_uuid    uuid,
  limit_count  integer,
  offset_count integer
)
returns table (
  id bigint, username text, title text, content text, images text[],
  likes int, isliked boolean, created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select gb.id, gb.username, gb.title, gb.content, gb.images::text[], gb.likes::int,
         exists (select 1 from public.likes l
                 where l.post_id = gb.id and l.user_id = user_uuid) as isliked,
         gb.created_at
  from public.gossipbar gb
  where gb.user_id = user_uuid
  order by gb.created_at desc
  limit limit_count offset offset_count;
$$;

-- Posts: toggle a like (returns TRUE if now liked, FALSE if unliked)
create or replace function public.toggle_like(p_userid uuid, p_postid bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  is_liked boolean;
begin
  if exists (select 1 from public.likes
             where user_id = p_userid and post_id = p_postid) then
    delete from public.likes where user_id = p_userid and post_id = p_postid;
    update public.gossipbar set likes = greatest(likes - 1, 0) where id = p_postid;
    return false;
  else
    insert into public.likes (user_id, post_id) values (p_userid, p_postid);
    update public.gossipbar set likes = likes + 1 where id = p_postid;
    return true;
  end if;
end;
$$;

-- Posts: delete ONLY your own post (ownership checked server-side)
create or replace function public.delete_gossipbar_post(p_userid uuid, p_postid bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.gossipbar
  where id = p_postid and user_id = p_userid;
  return found;
end;
$$;

-- Chat: send a message (username pulled from profiles server-side)
create or replace function public.insert_message(user_id uuid, message_text text)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.messages (user_id, username, message)
  select user_id, author.username, message_text
  from public.profiles author
  where author.id = user_id;
$$;

-- Chat: last 30 messages to hydrate the room on load
create or replace function public.fetch_live()
returns table (id bigint, username text, message text, created_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select id, username, message, created_at
  from public.messages
  order by created_at desc
  limit 30;
$$;

-- ---------------------------------------------------------------------------
-- 5. STORAGE — "gossip" bucket for post images (public, up to 2 per post)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('gossip', 'gossip', true)
on conflict (id) do nothing;

create policy "gossip_read" on storage.objects
  for select using (bucket_id = 'gossip');

create policy "gossip_insert" on storage.objects
  for insert to authenticated with check (bucket_id = 'gossip');

-- ---------------------------------------------------------------------------
-- 6. REALTIME — stream new messages to the Campus Connect chat
-- ---------------------------------------------------------------------------
alter publication supabase_realtime add table public.messages;